[project]
name = "allowlistapp"
version = "0.2.0"
description = "Flask webapp to allowlist IPs on nginx"
authors = [{ name = "Kieran Gee", email = "kieran.lost.the.game@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3,<4",
    "argon2-cffi>=25.1.0,<26",
    "waitress>=3.0.2,<4",
    "requests>=2.32.5,<3",
    "tomlkit>=0.14,<1",
    "pydantic>=2.0,<3",
    "pydantic-settings>=2.0,<3",
]

[dependency-groups]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "detect-test-pollution",
    "pytest-random-order",
    "pytest-subprocess",
    "responses",
    "jinja2",                # Flask depends on this, I have it here since config loading is templated for tests.
]
type = ["types-requests", "ty"]
lint = ["ruff>=0.15.0,<1"]
dev = [{ include-group = "test" }, { include-group = "type" }, { include-group = "lint" }]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.ruff]
cache-dir = "~/.cache/ruff"
line-length = 120

[tool.ruff.lint]
extend-fixable = ["B", "I001"] # KG I think this means something...
extend-unsafe-fixes = [
    "F401",
] # KG I don't like that this is fixed automatically (this doesnt work?)
select = ["ALL"] # KG Include absolutely all of Ruff's rules.
ignore = [
    # Modules
    "DJ",  # KG Django not required
    "DTZ", # KG no need to specify timezone for time objects
    "CPY", # Copyright in pyproject.toml

    # Specific rules
    "TD002",  # KG Verbose TODO, only I work on this project
    "TD003",  # KG Verbose TODO, only I work on this project
    "ISC001", # KG conflict in the formatter
    "COM812", # KG conflict in the formatter
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    # Modules
    "ARG", # KG Unused function args -> fixtures nevertheless are functionally relevant
    "FBT", # KG Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()

    # Specific rules
    "S101",   # KG asserts allowed in tests.
    "ANN201", # KG Not really needed for pytest.
    "SLF001", # KG Accessing private members is needed for testing.
    "INP001", # KG __init__.py not needed for PyTest.
    "PT004",  # KG monkeypatches don't return.
    "S311",   # KG I'll assume no real crypto will be done in PyTest.
]
"src/allowlistapp/auth/auth_types.py" = [
    "S106", # Not a hardcoded password
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 40

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov-context=test",
    "--cov=allowlistapp",
    "--cov-report=term",
    "--cov-report=html",
]
testpaths = ["tests"]

[tool.coverage.html]
show_contexts = true
